final_op: [0, 0, 0, 0, 0, 1, 1, 1]
neupi_non_effect_predicates: ['CalibrationTarget', 'HasCamera', 'HasInfrared', 'HasGeiger', 'ShootsChemX', 'ShootsChemY']

config:
  - name: "other"
    num_vectors_to_generate_list: [2, 2, 1, 2]
    domain_desc: ""
  - name: "neural_u_p1"
    types: ["satellite"]
    num_vectors_to_generate: 1
    # gt: [[1,0,0,0,0,0,0,0]]
    ent_idx: [0]
    architecture: 
      type: "MLP"
      layer_size: 32
      initializer: "xavier"
    optimizer:
      type: "AdamW"
      kwargs:
        lr: 0.001
    lr_scheduler:
      type: "StepLR"
      kwargs:
        step_size: 70
        gamma: 0.1
    batch_vect_num: 12
    batch_size: 512
    epochs: 100
    gumbel_temp: 0.66
    val_freq: 10
    num_iter: 5
    matrix_vec_try: 100
    search_tree_max_level: 1
    guidance_thresh: 0.05
    loss_thresh: 0.005
    skip_train: False
  
  - name: "neural_u_p2"
    types: ["object"]
    num_vectors_to_generate: 2
    # gt: [[0,0,0,1,0,0,0,0],[0,0,0,0,1,0,0,0]]
    ent_idx: [0]
    architecture:
      type: "MLP"
      layer_size: 32
      initializer: "xavier"
    optimizer:
      type: "AdamW"
      kwargs:
        lr: 0.001
    lr_scheduler:
      type: "StepLR"
      kwargs:
        step_size: 70
        gamma: 0.1
    batch_vect_num: 12
    ucb_kappa: 0.2
    batch_size: 512
    epochs: 100
    gumbel_temp: 0.66
    val_freq: 10
    num_iter: 5
    matrix_vec_try: 100
    search_tree_max_level: 1
    guidance_thresh: 0.05
    loss_thresh: 0.005
    skip_train: False

  - name: "neural_b_p3"
    types: ["satellite", "object"]
    ent_idx: [0, 0]
    num_vectors_to_generate: 2
    # gt: [[0,2,1,0,0,0,0,0],[1,0,0,0,0,0,0,0]]
    architecture:
      type: "MLP"
      layer_size: 128
      initializer: "xavier"
    optimizer:
      type: "AdamW"
      kwargs:
        lr: 0.001
    lr_scheduler:
      type: "StepLR"
      kwargs:
        step_size: 70
        gamma: 0.1
    batch_vect_num: 4
    ucb_kappa: 0.3
    batch_size: 512
    epochs: 200
    gumbel_temp: 0.66
    val_freq: 10
    num_iter: 70
    matrix_vec_try: 100
    search_tree_max_level: 1
    guidance_thresh: 0.1 # this predicate is harder to learn for nn
    loss_thresh: 0.005
    skip_train: False

  - name: "neural_b_p4"
    types: ["object", "satellite"]
    ent_idx: [0, 0]
    num_vectors_to_generate: 0
    # gt: [[0, 2, 1, 0, 0, 0, 0, 0]]
    architecture:
      type: "MLP"
      layer_size: 128
      initializer: "xavier"
    optimizer:
      type: "AdamW"
      kwargs:
        lr: 0.001
    lr_scheduler:
      type: "StepLR"
      kwargs:
        step_size: 70
        gamma: 0.1
    batch_vect_num: 4
    ucb_kappa: 0.3
    batch_size: 512
    epochs: 200
    gumbel_temp: 0.66
    val_freq: 10
    num_iter: 70
    matrix_vec_try: 100
    search_tree_max_level: 1
    guidance_thresh: 0.1
    loss_thresh: 0.005
    skip_train: False